### ISSUE TITLE
add code of conduct

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/sprint-pymc-data-umbrella#1]
We could add the full numfocus coc: https://github.com/numfocus/numfocus/blob/master/manual/numfocus-coc.md or a reduced version linking to the version on their website llike jupytercon did for example: https://jupytercon.com/codeofconduct/.

**Comment by mjhajharia** [comment]
added it in index.md!

**Comment by OriolAbril** [comment]
Great! Short version and link works great. 

Some minor comments:

* I would create the CODE_OF_CONDUCT.md file and then use the include directive to add that to the index. The short version is fine. This will make it more visible for people looking at github instead of the website as well as automatically pulling that in at https://github.com/pymc-devs/sprint-pymc-data-umbrella/community (which now defaults to the one I added at https://github.com/pymc-devs/.github)
* We should also include a link and mention the numfocus reporting form. It is great to have an email to report to which will always be much faster but it is also important to allow anonymous reports.
* Even though we are writing markdown (myst), the website is generated with sphinx which does not support non-consecutive header levels. That is, after a `##` title, in markdown we can use `#####` to change formatting, in sphinx `#####` raises a warning and is interpreted as `###`
